### ISSUE TITLE
Skipping Buildings?

### ISSUE THREAD

**Issue by pachacamac** [noncomputable/AgentMaps#4]
What would be the best approach to skip buildings altogether? I'm only looking to simulate agents on a street network and I want the street network to be considerably bigger than in the demos (whole city if possible). Awesome library btw! Thank you for your work!

**Comment by noncomputable** [comment]
Thank you! 

For the last parameter of `Agentmap.buildingify`, `units_data`, you can provide an empty feature collection like this: `{type:"FeatureCollection", features:[]}`, and no units will be built. If you just provide an empty object `{}`, Leaflet will throw `Uncaught Error: Invalid GeoJSON object`, but I might deal with that to make the "no units" option more convenient.
 
Alternatively, if you installed the package and are using a bundler, you can import `setupStreetFeatures` from [buildings.js](https://github.com/noncomputable/AgentMaps/blob/master/src/buildings.js) alone and call it in your agentmap's context to only build the streets. 

You could also just call `agentmap.buildingify` normally and then `agentmap.units.clearLayers()` or `map.removeLayer(agentmap.units)` to erase them, but that seems a little inefficient.

**Comment by pachacamac** [comment]
Thank you for your response! I think I tried providing an empty feature collection like you suggested but still ran into problems. I'm sure this was a problem on my end though. However I couldn't get any usable performance done when I used slightly bigger maps, like a full district or city. Did you manage to use it on bigger maps?

**Comment by noncomputable** [comment]
Ah, alright! Next time add reproduction info to make it easier for anyone looking at the issue to get to the bottom of it! I've added an issue template to make that more convenient.

If some dataset is giving you trouble, please share it so we can test. I'll put up a tool let users generate units and streets without having to load them in a browser; that should deal wtih any performance problems at setup.
